30/6/2020 14:19:9 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\ddbb.py\", line 69, in retrieve\n    broker.send(str.encode(\nAttributeError: 'NoneType' object has no attribute 'send'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\ddbb.py\", line 79, in retrieve\n    broker.connect((settings.broker, 2443))\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\ssl.py\", line 1342, in connect\n    self._real_connect(addr, False)\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\ssl.py\", line 1329, in _real_connect\n    super().connect(addr)\nConnectionRefusedError: [WinError 10061] No se puede establecer una conexi\u00f3n ya que el equipo de destino deneg\u00f3 expresamente dicha conexi\u00f3n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 713, in _handle_event\n    ret = handler(*args)\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\modules\\control.py\", line 19, in controlList\n    status = ddbb.retrieve(main[i][0], 0)\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\ddbb.py\", line 87, in retrieve\n    raise Exception(\nException: Timed out while waiting for response! Is broker up?\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC5AgBO", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/control\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=a8905520b6ab4926ab41061803923679; Content=1251; Username=efren@boyarizo.es; Session=edDAcY06SzTmFd4-IAp1XX3BwVDwGUBjhU0tCi0UGM0F9Yl0y5nkudVOfk-EMCs=\"}"}

30/6/2020 14:19:32 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\ddbb.py\", line 69, in retrieve\n    broker.send(str.encode(\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\ssl.py\", line 1175, in send\n    return super().send(data, flags)\nsocket.timeout: timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\ddbb.py\", line 79, in retrieve\n    broker.connect((settings.broker, 2443))\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\ssl.py\", line 1342, in connect\n    self._real_connect(addr, False)\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\ssl.py\", line 1329, in _real_connect\n    super().connect(addr)\nConnectionRefusedError: [WinError 10061] No se puede establecer una conexi\u00f3n ya que el equipo de destino deneg\u00f3 expresamente dicha conexi\u00f3n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 713, in _handle_event\n    ret = handler(*args)\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\modules\\control.py\", line 19, in controlList\n    status = ddbb.retrieve(main[i][0], 0)\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\ddbb.py\", line 87, in retrieve\n    raise Exception(\nException: Timed out while waiting for response! Is broker up?\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC5AgBO", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/control\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=a8905520b6ab4926ab41061803923679; Content=1251; Username=efren@boyarizo.es; Session=edDAcY06SzTmFd4-IAp1XX3BwVDwGUBjhU0tCi0UGM0F9Yl0y5nkudVOfk-EMCs=\"}"}

30/6/2020 14:20:37 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\ddbb.py\", line 69, in retrieve\n    broker.send(str.encode(\nAttributeError: 'NoneType' object has no attribute 'send'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\ddbb.py\", line 79, in retrieve\n    broker.connect((settings.broker, 2443))\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\ssl.py\", line 1342, in connect\n    self._real_connect(addr, False)\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\ssl.py\", line 1329, in _real_connect\n    super().connect(addr)\nConnectionRefusedError: [WinError 10061] No se puede establecer una conexi\u00f3n ya que el equipo de destino deneg\u00f3 expresamente dicha conexi\u00f3n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 713, in _handle_event\n    ret = handler(*args)\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\modules\\control.py\", line 19, in controlList\n    status = ddbb.retrieve(main[i][0], 0)\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\ddbb.py\", line 87, in retrieve\n    raise Exception(\nException: Timed out while waiting for response! Is broker up?\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC5A_en", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/control\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=6a051630f1bf4ab498d576fac829814d; Username=efren@boyarizo.es; Session=edDAcY06SzTmFd4-IAp1XX3BwVDwGUBjhU0tCi0UGM0F9Yl0y5nkudVOfk-EMCs=; Content=61e4\"}"}

30/6/2020 14:21:3 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\ddbb.py\", line 69, in retrieve\n    broker.send(str.encode(\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\ssl.py\", line 1175, in send\n    return super().send(data, flags)\nsocket.timeout: timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\ddbb.py\", line 79, in retrieve\n    broker.connect((settings.broker, 2443))\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\ssl.py\", line 1342, in connect\n    self._real_connect(addr, False)\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\ssl.py\", line 1329, in _real_connect\n    super().connect(addr)\nConnectionRefusedError: [WinError 10061] No se puede establecer una conexi\u00f3n ya que el equipo de destino deneg\u00f3 expresamente dicha conexi\u00f3n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 713, in _handle_event\n    ret = handler(*args)\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\modules\\control.py\", line 19, in controlList\n    status = ddbb.retrieve(main[i][0], 0)\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\ddbb.py\", line 87, in retrieve\n    raise Exception(\nException: Timed out while waiting for response! Is broker up?\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC5A_en", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/control\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=6a051630f1bf4ab498d576fac829814d; Username=efren@boyarizo.es; Session=edDAcY06SzTmFd4-IAp1XX3BwVDwGUBjhU0tCi0UGM0F9Yl0y5nkudVOfk-EMCs=; Content=61e4\"}"}

30/6/2020 14:36:41 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 711, in _handle_event\n    ret = handler()\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 22, in on_connect\n    if request.cookies.get('Content') != version:\nNameError: name 'version' is not defined\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC5EhcT", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/control\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=d3409cc1e2c24324bd2705c02ee4411d; Username=efren@boyarizo.es; Session=CysVxFAundEbdDyWAEbnyH-m5Bp1tFM2ADRQdla_sL9ZkiptQnmzRU10aKBXvWGzP6Kh; Content=&lt\"}"}

30/6/2020 14:49:30 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 111, in __getitem__\n    value = self.cache[key]\nKeyError: 'efren@boyarizo.es'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 711, in _handle_event\n    ret = handler()\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 22, in on_connect\n    if not check():\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 109, in check\n    if ddbb.sessions.get(user) == hash:\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 106, in get\n    return self[key]\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 114, in __getitem__\n    value = Unpickler(f).load()\n_pickle.UnpicklingError: pickle data was truncated\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC5HdNk", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/control\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=5420fcf46efd4faaa07c9fc6c660b1b8; Username=efren@boyarizo.es; Session=m2PFaGnKNOYeBcmzj9BSGOgHS2s5GMZRoXGa_3vWkORzhL8nnPM0K85MuNmjWFr0EMCPjLbJchDD4A==; Content=868c\"}"}

30/6/2020 14:49:51 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 111, in __getitem__\n    value = self.cache[key]\nKeyError: 'efren@boyarizo.es'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 711, in _handle_event\n    ret = handler()\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 22, in on_connect\n    if not check():\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 109, in check\n    if ddbb.sessions.get(user) == hash:\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 106, in get\n    return self[key]\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 114, in __getitem__\n    value = Unpickler(f).load()\n_pickle.UnpicklingError: pickle data was truncated\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC5HiSt", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/control\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=64b417ee0d164c78a40a974ed3df36a0; Username=efren@boyarizo.es; Session=m2PFaGnKNOYeBcmzj9BSGOgHS2s5GMZRoXGa_3vWkORzhL8nnPM0K85MuNmjWFr0EMCPjLbJchDD4A==; Content=e911\"}"}

30/6/2020 14:50:49 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 111, in __getitem__\n    value = self.cache[key]\nKeyError: 'efren@boyarizo.es'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 711, in _handle_event\n    ret = handler()\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 22, in on_connect\n    if not check():\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 109, in check\n    if ddbb.sessions.get(user) == hash:\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 106, in get\n    return self[key]\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 114, in __getitem__\n    value = Unpickler(f).load()\n_pickle.UnpicklingError: pickle data was truncated\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC5Hwji", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/control\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=2c03e739d24b44ab874b2ab5e0b78a6f; Username=efren@boyarizo.es; Session=m2PFaGnKNOYeBcmzj9BSGOgHS2s5GMZRoXGa_3vWkORzhL8nnPM0K85MuNmjWFr0EMCPjLbJchDD4A==; Content=3b78\"}"}

30/6/2020 14:52:0 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 111, in __getitem__\n    value = self.cache[key]\nKeyError: 'efren@boyarizo.es'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 711, in _handle_event\n    ret = handler()\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 22, in on_connect\n    if not check():\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 109, in check\n    if ddbb.sessions.get(user) == hash:\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 106, in get\n    return self[key]\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 114, in __getitem__\n    value = Unpickler(f).load()\n_pickle.UnpicklingError: pickle data was truncated\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC5IBvW", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/control\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=546853506c494b6187e1ecd17c6347c1; Username=efren@boyarizo.es; Session=m2PFaGnKNOYeBcmzj9BSGOgHS2s5GMZRoXGa_3vWkORzhL8nnPM0K85MuNmjWFr0EMCPjLbJchDD4A==; Content=ada3\"}"}

30/6/2020 14:52:24 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 111, in __getitem__\n    value = self.cache[key]\nKeyError: 'efren@boyarizo.es'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 711, in _handle_event\n    ret = handler()\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 22, in on_connect\n    if not check():\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 109, in check\n    if ddbb.sessions.get(user) == hash:\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 106, in get\n    return self[key]\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 114, in __getitem__\n    value = Unpickler(f).load()\n_pickle.UnpicklingError: pickle data was truncated\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC5IHmc", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/control\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=7e54a02e63a44c24b72d8a73b6f5211d; Username=efren@boyarizo.es; Session=m2PFaGnKNOYeBcmzj9BSGOgHS2s5GMZRoXGa_3vWkORzhL8nnPM0K85MuNmjWFr0EMCPjLbJchDD4A==; Content=c042\"}"}

30/6/2020 15:45:23 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 111, in __getitem__\n    value = self.cache[key]\nKeyError: 'efren@boyarizo.es'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 711, in _handle_event\n    ret = handler()\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 22, in on_connect\n    if not check():\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 109, in check\n    if ddbb.sessions.get(user) == hash:\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 106, in get\n    return self[key]\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 114, in __getitem__\n    value = Unpickler(f).load()\n_pickle.UnpicklingError: pickle data was truncated\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC5UQ3L", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/control\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=9df0ac03c4d6450f9ddd4760cf4f321d; Username=efren@boyarizo.es; Session=z2Cqj2UewDDG7cyskDrHJrkUnoS6AH_WfRX-E7HBQQhyDdfbCI4xtn2tpTSTMahtatPkjbvE9Ymn; Content=d590\"}"}

30/6/2020 16:24:51 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 111, in __getitem__\n    value = self.cache[key]\nKeyError: 'efren@boyarizo.es'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 711, in _handle_event\n    ret = handler()\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 22, in on_connect\n    if not check():\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 109, in check\n    if ddbb.sessions.get(user) == hash:\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 106, in get\n    return self[key]\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 114, in __getitem__\n    value = Unpickler(f).load()\n_pickle.UnpicklingError: pickle data was truncated\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC5dR_U", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/control\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=8166a1975a4e47e7a4dbd28876b5db6c; Username=efren@boyarizo.es; Session=h8ualxp8725jGYsKGticwicjARo4I8iDdxpGqAUVwfCOz4VPnC3wS-_vaqu5pd7rALZFj8o0yU6rwWu8; Content=980e\"}"}

30/6/2020 16:25:31 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 111, in __getitem__\n    value = self.cache[key]\nKeyError: 'efren@boyarizo.es'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 711, in _handle_event\n    ret = handler()\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 22, in on_connect\n    if not check():\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 109, in check\n    if ddbb.sessions.get(user) == hash:\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 106, in get\n    return self[key]\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 114, in __getitem__\n    value = Unpickler(f).load()\n_pickle.UnpicklingError: pickle data was truncated\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC5dblo", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/control\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=5e64a003766141f7a653ed5323a4919d; Username=efren@boyarizo.es; Session=h8ualxp8725jGYsKGticwicjARo4I8iDdxpGqAUVwfCOz4VPnC3wS-_vaqu5pd7rALZFj8o0yU6rwWu8; Content=faeb\"}"}

30/6/2020 17:12:44 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 111, in __getitem__\n    value = self.cache[key]\nKeyError: 'efren@boyarizo.es'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 711, in _handle_event\n    ret = handler()\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 22, in on_connect\n    if not check():\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 109, in check\n    if ddbb.sessions.get(user) == hash:\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 106, in get\n    return self[key]\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 114, in __getitem__\n    value = Unpickler(f).load()\n_pickle.UnpicklingError: pickle data was truncated\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC5oPYD", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/control\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=015b06954f154ee2b19c31882a863d20; Username=efren@boyarizo.es; Session=g3fxfFhqE-CRuEJpAth1uzq4rb_WnqUBZlwQVzrnZJh-WFneuQBGdxCqNAD2BrDXoWrt0bRZ5g==; Content=625e\"}"}

30/6/2020 17:12:52 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 111, in __getitem__\n    value = self.cache[key]\nKeyError: 'efren@boyarizo.es'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 711, in _handle_event\n    ret = handler()\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 22, in on_connect\n    if not check():\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 109, in check\n    if ddbb.sessions.get(user) == hash:\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 106, in get\n    return self[key]\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 114, in __getitem__\n    value = Unpickler(f).load()\n_pickle.UnpicklingError: pickle data was truncated\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC5oRXZ", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/manager\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=c481760b559a44be90455c59beef6beb; Username=efren@boyarizo.es; Session=g3fxfFhqE-CRuEJpAth1uzq4rb_WnqUBZlwQVzrnZJh-WFneuQBGdxCqNAD2BrDXoWrt0bRZ5g==; Content=625e\"}"}

30/6/2020 17:12:57 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 111, in __getitem__\n    value = self.cache[key]\nKeyError: 'efren@boyarizo.es'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 711, in _handle_event\n    ret = handler()\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 22, in on_connect\n    if not check():\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 109, in check\n    if ddbb.sessions.get(user) == hash:\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 106, in get\n    return self[key]\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 114, in __getitem__\n    value = Unpickler(f).load()\n_pickle.UnpicklingError: pickle data was truncated\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC5oSaj", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/control\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=bd2952f7f5ce403999794a4a28e11ce9; Username=efren@boyarizo.es; Session=g3fxfFhqE-CRuEJpAth1uzq4rb_WnqUBZlwQVzrnZJh-WFneuQBGdxCqNAD2BrDXoWrt0bRZ5g==; Content=625e\"}"}

30/6/2020 17:13:51 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 111, in __getitem__\n    value = self.cache[key]\nKeyError: 'efren@boyarizo.es'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 713, in _handle_event\n    ret = handler(*args)\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 56, in on_disconnect\n    if not check():\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 109, in check\n    if ddbb.sessions.get(user) == hash:\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 106, in get\n    return self[key]\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 114, in __getitem__\n    value = Unpickler(f).load()\n_pickle.UnpicklingError: pickle data was truncated\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC5oSaj", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/control\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=bd2952f7f5ce403999794a4a28e11ce9; Username=efren@boyarizo.es; Session=g3fxfFhqE-CRuEJpAth1uzq4rb_WnqUBZlwQVzrnZJh-WFneuQBGdxCqNAD2BrDXoWrt0bRZ5g==; Content=625e\"}"}

30/6/2020 17:13:51 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 111, in __getitem__\n    value = self.cache[key]\nKeyError: 'efren@boyarizo.es'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 711, in _handle_event\n    ret = handler()\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 22, in on_connect\n    if not check():\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 109, in check\n    if ddbb.sessions.get(user) == hash:\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 106, in get\n    return self[key]\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 114, in __getitem__\n    value = Unpickler(f).load()\n_pickle.UnpicklingError: pickle data was truncated\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC5ofwx", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/control\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=5ab890e947104ca5ae00ee44c2685114; Username=efren@boyarizo.es; Session=g3fxfFhqE-CRuEJpAth1uzq4rb_WnqUBZlwQVzrnZJh-WFneuQBGdxCqNAD2BrDXoWrt0bRZ5g==; Content=625e\"}"}

30/6/2020 17:14:4 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 111, in __getitem__\n    value = self.cache[key]\nKeyError: 'efren@boyarizo.es'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 713, in _handle_event\n    ret = handler(*args)\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 56, in on_disconnect\n    if not check():\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 109, in check\n    if ddbb.sessions.get(user) == hash:\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 106, in get\n    return self[key]\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 114, in __getitem__\n    value = Unpickler(f).load()\n_pickle.UnpicklingError: pickle data was truncated\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC5ofwx", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/control\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=5ab890e947104ca5ae00ee44c2685114; Username=efren@boyarizo.es; Session=g3fxfFhqE-CRuEJpAth1uzq4rb_WnqUBZlwQVzrnZJh-WFneuQBGdxCqNAD2BrDXoWrt0bRZ5g==; Content=625e\"}"}

30/6/2020 17:14:4 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 111, in __getitem__\n    value = self.cache[key]\nKeyError: 'efren@boyarizo.es'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 711, in _handle_event\n    ret = handler()\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 22, in on_connect\n    if not check():\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 109, in check\n    if ddbb.sessions.get(user) == hash:\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 106, in get\n    return self[key]\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 114, in __getitem__\n    value = Unpickler(f).load()\n_pickle.UnpicklingError: pickle data was truncated\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC5oi-l", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/control\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=1f69892d678f4ab1af65ffdddceda8a3; Username=efren@boyarizo.es; Session=g3fxfFhqE-CRuEJpAth1uzq4rb_WnqUBZlwQVzrnZJh-WFneuQBGdxCqNAD2BrDXoWrt0bRZ5g==; Content=625e\"}"}

30/6/2020 17:14:4 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 111, in __getitem__\n    value = self.cache[key]\nKeyError: 'efren@boyarizo.es'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 713, in _handle_event\n    ret = handler(*args)\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 56, in on_disconnect\n    if not check():\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 109, in check\n    if ddbb.sessions.get(user) == hash:\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 106, in get\n    return self[key]\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 114, in __getitem__\n    value = Unpickler(f).load()\n_pickle.UnpicklingError: pickle data was truncated\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC5oRXZ", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/manager\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=c481760b559a44be90455c59beef6beb; Username=efren@boyarizo.es; Session=g3fxfFhqE-CRuEJpAth1uzq4rb_WnqUBZlwQVzrnZJh-WFneuQBGdxCqNAD2BrDXoWrt0bRZ5g==; Content=625e\"}"}

30/6/2020 17:22:45 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 111, in __getitem__\n    value = self.cache[key]\nKeyError: 'efren@boyarizo.es'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 713, in _handle_event\n    ret = handler(*args)\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 56, in on_disconnect\n    if not check():\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 109, in check\n    if ddbb.sessions.get(user) == hash:\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 106, in get\n    return self[key]\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 114, in __getitem__\n    value = Unpickler(f).load()\n_pickle.UnpicklingError: pickle data was truncated\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC5oPYD", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/control\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=015b06954f154ee2b19c31882a863d20; Username=efren@boyarizo.es; Session=g3fxfFhqE-CRuEJpAth1uzq4rb_WnqUBZlwQVzrnZJh-WFneuQBGdxCqNAD2BrDXoWrt0bRZ5g==; Content=625e\"}"}

30/6/2020 20:39:50 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\ddbb.py\", line 69, in retrieve\n    broker.send(str.encode(\nAttributeError: 'NoneType' object has no attribute 'send'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\ddbb.py\", line 79, in retrieve\n    broker.connect((settings.broker, 2443))\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\ssl.py\", line 1342, in connect\n    self._real_connect(addr, False)\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\ssl.py\", line 1329, in _real_connect\n    super().connect(addr)\nConnectionRefusedError: [WinError 10061] No se puede establecer una conexi\u00f3n ya que el equipo de destino deneg\u00f3 expresamente dicha conexi\u00f3n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 713, in _handle_event\n    ret = handler(*args)\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\modules\\control.py\", line 19, in controlList\n    status = ddbb.retrieve(main[i][0], 0)\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\ddbb.py\", line 87, in retrieve\n    raise Exception(\nException: Timed out while waiting for response! Is broker up?\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC6Xodb", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/control\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=cbe4455ff0e34f4e88c232ae7d1c5fae; Content=fb06; Username=efren@boyarizo.es; Session=iKPehdc0_ysLPNHtrxZUYcGAPaOA30QZk_ilu-7yFzREF2AGC2aO0E0XmTClcz57dxkZVQotChsg8DE=\"}"}

30/6/2020 20:40:40 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\ddbb.py\", line 69, in retrieve\n    broker.send(str.encode(\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\ssl.py\", line 1175, in send\n    return super().send(data, flags)\nsocket.timeout: timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\ddbb.py\", line 79, in retrieve\n    broker.connect((settings.broker, 2443))\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\ssl.py\", line 1342, in connect\n    self._real_connect(addr, False)\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\ssl.py\", line 1329, in _real_connect\n    super().connect(addr)\nConnectionRefusedError: [WinError 10061] No se puede establecer una conexi\u00f3n ya que el equipo de destino deneg\u00f3 expresamente dicha conexi\u00f3n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 713, in _handle_event\n    ret = handler(*args)\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\modules\\control.py\", line 19, in controlList\n    status = ddbb.retrieve(main[i][0], 0)\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\ddbb.py\", line 87, in retrieve\n    raise Exception(\nException: Timed out while waiting for response! Is broker up?\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC6Xodb", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/control\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=cbe4455ff0e34f4e88c232ae7d1c5fae; Content=fb06; Username=efren@boyarizo.es; Session=iKPehdc0_ysLPNHtrxZUYcGAPaOA30QZk_ilu-7yFzREF2AGC2aO0E0XmTClcz57dxkZVQotChsg8DE=\"}"}

30/6/2020 21:40:9 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 111, in __getitem__\n    value = self.cache[key]\nKeyError: 'efren@boyarizo.es'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 711, in _handle_event\n    ret = handler()\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 22, in on_connect\n    if not check():\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 109, in check\n    if ddbb.sessions.get(user) == hash:\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 106, in get\n    return self[key]\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 114, in __getitem__\n    value = Unpickler(f).load()\n_pickle.UnpicklingError: pickle data was truncated\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC6lcmV", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/manager\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=bd7bb6f4165b47139e06174af66fd9a0; Username=efren@boyarizo.es; Session=-NuCAhlblI1DcvEFFMi6MDQBrTIpytCszQ7-uhDRjO2uhrhk-M4SO4bo7T3UoYBvXBdLthBXdJcy; Content=df2e\"}"}

30/6/2020 21:40:44 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 111, in __getitem__\n    value = self.cache[key]\nKeyError: 'efren@boyarizo.es'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 711, in _handle_event\n    ret = handler()\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 22, in on_connect\n    if not check():\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 109, in check\n    if ddbb.sessions.get(user) == hash:\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 106, in get\n    return self[key]\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 114, in __getitem__\n    value = Unpickler(f).load()\n_pickle.UnpicklingError: pickle data was truncated\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC6ll9k", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/manager\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=56bfa83546bb45aa9c820c8a3c9236a8; Username=efren@boyarizo.es; Session=-NuCAhlblI1DcvEFFMi6MDQBrTIpytCszQ7-uhDRjO2uhrhk-M4SO4bo7T3UoYBvXBdLthBXdJcy; Content=9ccd\"}"}

30/6/2020 21:44:0 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 111, in __getitem__\n    value = self.cache[key]\nKeyError: 'efren@boyarizo.es'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 711, in _handle_event\n    ret = handler()\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 22, in on_connect\n    if not check():\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 109, in check\n    if ddbb.sessions.get(user) == hash:\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 106, in get\n    return self[key]\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 114, in __getitem__\n    value = Unpickler(f).load()\n_pickle.UnpicklingError: pickle data was truncated\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC6mV0Q", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/manager\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=6bd69cc0a5ca4716934ee22577950a74; Username=efren@boyarizo.es; Session=PE0jzYtfltGqLVFyAE55sm-77yJey9bVprl5--2CYH3kvLZ2umLr72MBQlDZgoEZryDfJgYOr8nlPPc2; Content=f546\"}"}

30/6/2020 21:45:51 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 111, in __getitem__\n    value = self.cache[key]\nKeyError: 'efren@boyarizo.es'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 711, in _handle_event\n    ret = handler()\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 22, in on_connect\n    if not check():\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 109, in check\n    if ddbb.sessions.get(user) == hash:\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 106, in get\n    return self[key]\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 114, in __getitem__\n    value = Unpickler(f).load()\n_pickle.UnpicklingError: pickle data was truncated\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC6mw9L", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/manager\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=4dd1a30db0534b80a198b3bfa77efcd8; Username=efren@boyarizo.es; Session=PE0jzYtfltGqLVFyAE55sm-77yJey9bVprl5--2CYH3kvLZ2umLr72MBQlDZgoEZryDfJgYOr8nlPPc2; Content=acc6\"}"}

30/6/2020 21:46:4 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 111, in __getitem__\n    value = self.cache[key]\nKeyError: 'efren@boyarizo.es'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 711, in _handle_event\n    ret = handler()\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 22, in on_connect\n    if not check():\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 109, in check\n    if ddbb.sessions.get(user) == hash:\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 106, in get\n    return self[key]\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 114, in __getitem__\n    value = Unpickler(f).load()\n_pickle.UnpicklingError: pickle data was truncated\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC6mzHa", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/manager\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=61767b53340e4581b4eb9b01aae74ddf; Username=efren@boyarizo.es; Session=PE0jzYtfltGqLVFyAE55sm-77yJey9bVprl5--2CYH3kvLZ2umLr72MBQlDZgoEZryDfJgYOr8nlPPc2; Content=67df\"}"}

30/6/2020 21:46:24 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 111, in __getitem__\n    value = self.cache[key]\nKeyError: 'efren@boyarizo.es'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 711, in _handle_event\n    ret = handler()\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 22, in on_connect\n    if not check():\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 109, in check\n    if ddbb.sessions.get(user) == hash:\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 106, in get\n    return self[key]\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 114, in __getitem__\n    value = Unpickler(f).load()\n_pickle.UnpicklingError: pickle data was truncated\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC6n29s", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/manager\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=4711afebc13b4f3198adca4026c27d1b; Username=efren@boyarizo.es; Session=PE0jzYtfltGqLVFyAE55sm-77yJey9bVprl5--2CYH3kvLZ2umLr72MBQlDZgoEZryDfJgYOr8nlPPc2; Content=152b\"}"}

30/6/2020 21:46:54 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 111, in __getitem__\n    value = self.cache[key]\nKeyError: 'efren@boyarizo.es'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 711, in _handle_event\n    ret = handler()\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 22, in on_connect\n    if not check():\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 109, in check\n    if ddbb.sessions.get(user) == hash:\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 106, in get\n    return self[key]\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 114, in __getitem__\n    value = Unpickler(f).load()\n_pickle.UnpicklingError: pickle data was truncated\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC6n9c8", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/manager\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=950f3c917bd34d438ac95996cd670dc5; Username=efren@boyarizo.es; Session=PE0jzYtfltGqLVFyAE55sm-77yJey9bVprl5--2CYH3kvLZ2umLr72MBQlDZgoEZryDfJgYOr8nlPPc2; Content=c735\"}"}

30/6/2020 21:47:24 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 111, in __getitem__\n    value = self.cache[key]\nKeyError: 'efren@boyarizo.es'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 711, in _handle_event\n    ret = handler()\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 22, in on_connect\n    if not check():\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 109, in check\n    if ddbb.sessions.get(user) == hash:\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 106, in get\n    return self[key]\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 114, in __getitem__\n    value = Unpickler(f).load()\n_pickle.UnpicklingError: pickle data was truncated\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC6nH0K", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/manager\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=89bd55f225cb4b6aaa8b49c4446cdc0e; Username=efren@boyarizo.es; Session=PE0jzYtfltGqLVFyAE55sm-77yJey9bVprl5--2CYH3kvLZ2umLr72MBQlDZgoEZryDfJgYOr8nlPPc2; Content=93ed\"}"}

30/6/2020 21:47:36 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 111, in __getitem__\n    value = self.cache[key]\nKeyError: 'efren@boyarizo.es'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 711, in _handle_event\n    ret = handler()\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 22, in on_connect\n    if not check():\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 109, in check\n    if ddbb.sessions.get(user) == hash:\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 106, in get\n    return self[key]\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 114, in __getitem__\n    value = Unpickler(f).load()\n_pickle.UnpicklingError: pickle data was truncated\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC6nJwl", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/control\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=b93f46d401f2419d821de7072e208480; Username=efren@boyarizo.es; Session=PE0jzYtfltGqLVFyAE55sm-77yJey9bVprl5--2CYH3kvLZ2umLr72MBQlDZgoEZryDfJgYOr8nlPPc2; Content=93ed\"}"}

30/6/2020 21:48:47 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 111, in __getitem__\n    value = self.cache[key]\nKeyError: 'efren@boyarizo.es'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 713, in _handle_event\n    ret = handler(*args)\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 56, in on_disconnect\n    if not check():\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 109, in check\n    if ddbb.sessions.get(user) == hash:\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 106, in get\n    return self[key]\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 114, in __getitem__\n    value = Unpickler(f).load()\n_pickle.UnpicklingError: pickle data was truncated\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC6nH0K", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/manager\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=89bd55f225cb4b6aaa8b49c4446cdc0e; Username=efren@boyarizo.es; Session=PE0jzYtfltGqLVFyAE55sm-77yJey9bVprl5--2CYH3kvLZ2umLr72MBQlDZgoEZryDfJgYOr8nlPPc2; Content=93ed\"}"}

30/6/2020 21:48:51 → {"error": "Traceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 111, in __getitem__\n    value = self.cache[key]\nKeyError: 'efren@boyarizo.es'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\site-packages\\flask_socketio\\__init__.py\", line 713, in _handle_event\n    ret = handler(*args)\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 56, in on_disconnect\n    if not check():\n  File \"C:\\Users\\efrenbg1\\ownCloud\\Proyectos\\rmote.app\\libs\\sessions.py\", line 109, in check\n    if ddbb.sessions.get(user) == hash:\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 106, in get\n    return self[key]\n  File \"C:\\Users\\efrenbg1\\AppData\\Local\\Programs\\Python\\Python38-32\\lib\\shelve.py\", line 114, in __getitem__\n    value = Unpickler(f).load()\n_pickle.UnpicklingError: pickle data was truncated\n", "url": "http://localhost/socket.io/?EIO=3&transport=polling&t=NC6nJwl", "headers": "{\"Content-Type\": \"text/plain\", \"Host\": \"localhost\", \"Connection\": \"keep-alive\", \"Accept\": \"*/*\", \"User-Agent\": \"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Mobile Safari/537.36\", \"Sec-Fetch-Site\": \"same-origin\", \"Sec-Fetch-Mode\": \"cors\", \"Sec-Fetch-Dest\": \"empty\", \"Referer\": \"http://localhost/control\", \"Accept-Encoding\": \"gzip, deflate, br\", \"Accept-Language\": \"en,es-ES;q=0.9,es;q=0.8\", \"Cookie\": \"io=b93f46d401f2419d821de7072e208480; Username=efren@boyarizo.es; Session=PE0jzYtfltGqLVFyAE55sm-77yJey9bVprl5--2CYH3kvLZ2umLr72MBQlDZgoEZryDfJgYOr8nlPPc2; Content=93ed\"}"}

